const oqtuvchiObj = [
  {
    oqtuvchiID: 1,
    guruhlari: [1, 3],
    fullName: 'Jamoliddin Najmiddinov',
    avatar: 'https://i0.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1',
    telifonRaqam: '(90) 212-22-15',
    hisobHolati: 200.000,
    holati: 'Muzlatilgan',
    vaqti: 'Yanvar 26, 2020',
  },
  {
    oqtuvchiID: 2,
    guruhlari: [2],
    fullName: 'Valibek Nasimov',
    avatar: 'https://i0.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1',
    telifonRaqam: '(99) 312-54-15',
    hisobHolati: 200.000,
    holati: 'Activ',
    vaqti: 'Yanvar 29, 2020',
  },
  {
    oqtuvchiID: 3,
    guruhlari: [4],
    fullName: 'Karmberdi Aliyev',
    avatar: 'https://raw.githubusercontent.com/AntoineKahlouche/avataaars/HEAD/example.png',
    telifonRaqam: '(93) 512-12-17',
    hisobHolati: 200.000,
    holati: 'Activ',
    vaqti: 'Mart 1, 2020',
  },
  {
    oqtuvchiID: 4,
    guruhlari: [5],
    fullName: 'Alisher Xazratov',
    avatar: 'https://wilcity.com/wp-content/uploads/2019/02/avataaars.png',
    telifonRaqam: '(91) 122-02-52',
    hisobHolati: 0,
    holati: 'Activ',
    vaqti: 'Yanvar 26 2020',
  },
  {
    oqtuvchiID: 5,
    guruhlari: [6, 7],
    fullName: 'Elmurod Toshqulov',
    avatar: 'https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg',
    telifonRaqam: '(95) 012-32-16',
    hisobHolati: 0,
    holati: 'Activ',
    vaqti: 'Fevral 28, 2020',
  },
  {
    oqtuvchiID: 6,
    guruhlari: [8],
    fullName: 'Jamoliddin Najmiddinov',
    avatar: 'https://img.favpng.com/18/18/18/computer-icons-icon-design-avatar-png-favpng-X29r5WhWMXVYvNsYXkR4iBgwf.jpg',
    telifonRaqam: '(90) 212-22-15',
    hisobHolati: 200.000,
    holati: 'Activ',
    vaqti: 'Yanvar 26, 2020',
  },
  {
    oqtuvchiID: 8,
    guruhlari: [9],
    fullName: 'Valibek Nasimov',
    avatar: 'https://png.pngtree.com/png-vector/20191101/ourmid/pngtree-businessman-avatar-icon-flat-style-png-image_1917273.jpg',
    telifonRaqam: '(99) 812-92-05',
    hisobHolati: 200.000,
    holati: 'Activ',
    vaqti: 'Yanvar 29, 2020',
  }
]

export default oqtuvchiObj