const oquvchiObj = [
  {
    oqivchiID: 1,
    guruhlari: [1, 3],
    firstName: 'Jamoliddin',
    lastName: 'Najmiddinov',
    avatar: 'https://i0.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1',
    chegirmasi: 5,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Yanvar 26, 2020',
  },
  {
    oqivchiID: 2,
    guruhlari: [1],
    firstName: 'Valibek',
    lastName: 'Nasimov',
    avatar: 'https://i0.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Yanvar 29, 2020',
  },
  {
    oqivchiID: 3,
    guruhlari: [1, 2],
    firstName: 'Karmberdi',
    lastName: 'Aliyev',
    avatar: 'https://raw.githubusercontent.com/AntoineKahlouche/avataaars/HEAD/example.png',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Mart 1, 2020',
  },
  {
    oqivchiID: 4,
    guruhlari: [1],
    firstName: 'Alisher',
    lastName: 'Xazratov',
    avatar: 'https://wilcity.com/wp-content/uploads/2019/02/avataaars.png',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 0,
    vaqti: 'Yanvar 26 2020',
  },
  {
    oqivchiID: 5,
    guruhlari: [1, 3, 5],
    firstName: 'Elmurod',
    lastName: 'Toshqulov',
    avatar: 'https://icon-library.com/images/avatar-icon-images/avatar-icon-images-4.jpg',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 0,
    vaqti: 'Fevral 28, 2020',
  },
  {
    oqivchiID: 6,
    guruhlari: [1, 3, 4],
    firstName: 'Jamoliddin',
    lastName: 'Najmiddinov',
    avatar: 'https://img.favpng.com/18/18/18/computer-icons-icon-design-avatar-png-favpng-X29r5WhWMXVYvNsYXkR4iBgwf.jpg',
    chegirmasi: 5,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Yanvar 26, 2020',
  },
  {
    oqivchiID: 8,
    guruhlari: [1],
    firstName: 'Valibek',
    lastName: 'Nasimov',
    avatar: 'https://png.pngtree.com/png-vector/20191101/ourmid/pngtree-businessman-avatar-icon-flat-style-png-image_1917273.jpg',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Yanvar 29, 2020',
  },
  {
    oqivchiID: 9,
    guruhlari: [1, 3],
    firstName: 'Akbarali',
    lastName: 'Tengelov',
    avatar: 'https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Yanvar 15, 2020',
  },
  {
    oqivchiID: 10,
    guruhlari: [1, 2, 3],
    firstName: 'Akbarali',
    lastName: 'Tengelov',
    avatar: 'https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg',
    chegirmasi: 0,
    oylikTolovi: 200.000,
    hisobidagiQoldiq: 200.000,
    vaqti: 'Yanvar 15, 2020',
  },
]

export default oquvchiObj
